### ISSUE TITLE
Just dont get it!!!!

### ISSUE THREAD

**Issue by jonbuck16** [thymeleaf/thymeleaf-testing#13]
I am trying to execute a test on a text based template and the tests fail and I really do not understand what the output is telling me, it just makes no sense to me... obtained/expected.. the output happens to be what the template has created during execution, I thought it wasn't bothered about whitespace but maybe it is as the difference in the output looks to be space but I just don't understand how to interpret the message...

So in constructing the test I set the output to be exactly what Thymeleaf generated i.e. copy and paste but the tests fail...

The only thing I can think of is that the template has a decision based on a boolean property in the context and I am not 100% sure that I am constructing or setting that property correctly in the test file so can I ask you to confirm how you would set a boolean property in the context in the thtest file? as there are no examples in the docs, just the easiest and most obvious one i.e. a String...

I also could really do with understanding how you go about debugging a test...  is there anyway for it to spit out what the test engine has generated for example? that would help me understand and see what has been generated..

**Comment by danielfernandez** [comment]
Tests are only matched by generated output vs value of the `%OUTPUT` directive. The context is not matched, only the results of the execution of the template (for the specified context). As for how the template result is matched, non-HTML-significant whitespace is ignored unless the `%EXACT_MATCH` directive is set to true in the test.

If with *how to set a variable* you mean inside a `%CONTEXT` directive, that is just `true` or `false`. Values for context properties are specified as OGNL expressions, and `true`/`false` are valid boolean OGNL expressions.

Anyway, if you could copy+paste parts of your test, or the test results, it would help diagnosing what is going wrong for you.

**Comment by jonbuck16** [comment]
OK so I get that the tests are matching a generated output (using the input and context values) against a static version specified in the output section of the test file, that is perfect however the bit that is puzzling is that I have taken the output from my real code and used that to compare against and it is this that isn't matching..  which given it's simple nature is a bit puzzling...

Thanks for confirming the setting of a Boolean, I did have that right but when it's not working and no way of confirming what has been set, you start to think of what is wrong and with no examples I wasn't sure..

Just so you are aware I am not generating HTML and this is not a Web Application that I am dealing with, I just need to generate plain text with values and sections injected based on the context whose output is then fed into something else..

Output
[test_output.txt](https://github.com/thymeleaf/thymeleaf-testing/files/1362379/test_output.txt)

Test File
[thtest_file.txt](https://github.com/thymeleaf/thymeleaf-testing/files/1362394/thtest_file.txt)

**Comment by danielfernandez** [comment]
OK, so if this is `TEXT` mode, then matching will be always *exact*. So whitespace will be important.

Not only that, but also note that line feeding will be compared too. So maybe there is a difference in line feeds in your input and output files? (e.g. `<CR><LF>` in one vs `<LF>` in the other). Or maybe a difference in charset/encoding?

**Comment by danielfernandez** [comment]
If on an UNIX/Linux system, you could try and use `diff` to compare those files, or even `cmp -b` to compare byte-by-byte.

**Comment by danielfernandez** [comment]
Closing due to user inactivity
